sudo: required

language: php
php:
- '7.1.9'

branches:
  only:
  - master

# travis runtime environment from here or settings. : https://docs.travis-ci.com/user/environment-variables/
env:
  global:
  - ZIP_FILE="php-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"

  # travis-ci secure doc : https://docs.travis-ci.com/user/encryption-keys/
  # before install travis , first install ruby & gem
  # $ gem install travis
  # $ travis encrypt SOMEVAR="secretvalue"

  # AWS_ACCESS_KEY_ID_DEV
  - secure: ""
  # AWS_SECRET_ACCESS_KEY_DEV
  - secure: ""
  # AWS_ACCESS_KEY_ID_STG
  - secure: ""
  # AWS_SECRET_ACCESS_KEY_STG
  - secure: ""
  # AWS_ACCESS_KEY_ID_PROD , value : AKI....QMQ
  - secure: "CcLNLCGd0QROQ56KXMAol+x71Ro1TdFMi96an5hszppkdzXyD+BkI03IMNJK3zs8JgxchFdkJmqOt64NhgX5svfc2erNkk0lwikHBuWe++qYwumNTBZi89aM9diSOiVZArZzTFqe1NcJmL2mFhen+RD2U5JP7KTnkUFZnhzlc0fpoYHa9q2Q4s8gCYcj4TDIKo/ZV5bxFoNhEC1VCiHaDt6B9USlwZkrTzJ7RP0/AduiAT09xb5uXk905rJN8DUB9YSo3yxivf/bvcdABopcvkTmmeWhcGu1G0M8o1jVbyc4fu+Cs0Du0zD9varFDPA3SKuhOPgwTXVK+o3A/nbP0+tBrdmtIAwHn+j043uWTaAaUf4ZLsY6T8JDVhEN6Ma/25qCzel1mrSObyeFvZKDTJwh9b8LYPFl9CR7WVCUeQDgVKK3VsDI4vyofLc++tblmdise1QXE/verTbLR4hc1GWXIE2vJR3nLkF+FUf3bosfapqB2xu4wgcWvTyUIfYOgK4RtRD6CNy3IvLEXw2DPeXLQjduB6lgePfJp41la/1Pl75TrRt8dYpQlk7UCL+CGJJv/JRxOzGE17/m2N9WIaC60ws8p8ihcd+ie4EaRZxf67iqlgIU3T58VSh6VFNo+EnB9WUFsjbLlbKqeyW7y047Z1HOQ9rmyEwKuJaoWXM="
  # AWS_SECRET_ACCESS_KEY_PROD
  - secure: "VqzIpk0cC8jqirfmBZYum9Zzu8lj9EuHSHOPoZ8rRyJLKqJMpyVZ0LaPF2Yewp/UjDghi+9478Ddh5pb6HqDtA2mD2KBH3ci7sBnpzaX/8Q3LzRqZpRjgWCyS+1g1ue8gzh2NPVVTRsIg376QaRZv4SbffFVngkiWGpXTW5m46CgpTaJtRHkkkgJ/PFwkGUnlAdGiCiryRe/ydfh057wDezH3DqonM3CKGRtE2x9Zzs3cAvVN/NukerbtwtqtOyrOgTu3ukRXZxyMYcfteVuVh/iIXxonhd2ru0B33oPSK06+4I117ENd2GK/pmT6AnI6Z/LyGUyIDN3TklXpVD6fq0UTob8fYwECw/rHF5GYlUXbbuS6wLlMzQ/R9MMfIuIEJZ/o/g+jUbOCvR4hLT8kkaFllCnBrN9OEv7wVYUrKLqfrpVEhXTQyn60kIb8ONc4rLLXRV9mInZ1SfoaFUsq0FzE6Fzfy6KLUQD5q2WMsJWr/xPlf/jniwhNLHVWbT0FCPaRk+MDooY43fqKwl/5cA83YAViLSOLPNqfWckailaw+uMYPeSm9M/4LbRakc2LNIjZlfhv7ycPbuR9G4/awbM5icBcJxYN39KANGBa1d1fRCZdb/ttzxttUEzDkkA7k//04Jt1+CTlOPO7tivwP1wys48/ogaIjER/EmveKM="

  # global variables
  - AWS_ACCESS_KEY_ID=''
  - AWS_SECRET_ACCESS_KEY=''
  - AWS_REGION='ap-northeast-1'
  - CODEDEPLOY_APP_NAME=''
  - CODEDEPLOY_GROUP=''


# notification - https://docs.travis-ci.com/user/notifications
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: never # default: change
#     on_failure: always # default: always
# integration to slack , setup on slack travis-ci app
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    rooms:
    - secure: "KskRNYcARlfAkKcdqVhkvu+OUNS3/hPHoC6UUYLMvGPICc2abv7imG1KomOTBHcXmJnWpwekX1jWtp07oG4cb7lURPWHTqrQSRU5Ddd48znudzd9nxcxA+5Yz2Rp8Bgud2rVLf8Dysje8hkQdtNBMs3wDJIH8iBg9n6O7FCi9KZNtZL71+DV9Nl5KwLZRc1aCAYTHFg9THlHlfcJl6VaoEJMIDAoRB2CKTBPhx/NERhesrHUUB9913MhjSrAj7k6CpyHFh/AScycogZ8B456tAqpPrzEGdig0iAImdpXbLCBRJ/DwZY9OgzGuYyqcvG62JNBV8NWxoDFdMBIB/vTE7clZMIf3Kt0W7nJPlDCP8a0IIwl29akIzd1VCzp/EL0LNlXBNGC6VBacaMns/TEmPgcU1DIz8uYjNi1nrDUB20fdv7scAs/3cr9RybGIeAJEZKRSUEiWk+2D2ZId5SRy2Ka8MWLdIKWJKOWhA3rItdFJAvAgs9Ic0kWEFlXntSSXd55eQivuHwmWOBdmMCq9l3aCMGxd/9wfQXI4fs9XUuwKg+2+Bg7oU1c8RLJeMbHVWbKXTMZJIt3/DQrjJBs94MA2IZ0oyOJBd5SLDOBQZ4DgAR7Vn0RINqBFVFGuX9GdNN3yeq8cFnRD3+LZxaIplGQBuNso7e+FHHzhR12lYg="

cache:
  directories:
  - $COMPOSER_CACHE_DIR
  - $HOME/.composer/cache




# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
- set -e
- echo `date +"%Y-%m-%d %H:%M:%S"`
- echo $TRAVIS_BRANCH
- if [[ $TRAVIS_BRANCH == "dev" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV;
    S3_BUCKET='';
    CODEDEPLOY_APP='';
    CODEDEPLOY_GROUP='';
  fi
- if [[ $TRAVIS_BRANCH == "staging" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STG;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STG;
    S3_BUCKET='';
    CODEDEPLOY_APP='';
    CODEDEPLOY_GROUP='';
  fi
- if [[ $TRAVIS_BRANCH == "master" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD;
    S3_BUCKET='afgsfhdyur5joi868682333';
    CODEDEPLOY_APP='a1-EC2-CodeDeploy';
    CODEDEPLOY_GROUP='ec2';
  fi


# put testing scripts here
script:
- echo 'script step...'

before_deploy:
- cd "$TRAVIS_BUILD_DIR";
  mkdir "$TRAVIS_BUILD_DIR/zip";
  zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE" *


deploy:
- provider: S3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  local_dir: $TRAVIS_BUILD_DIR/zip
  bucket: $S3_BUCKET
  skip_cleanup: true
  on:
    all_branches: true

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  bucket: $S3_BUCKET
  key: $ZIP_FILE
  bundle_type: zip
  application: $CODEDEPLOY_APP
  deployment_group: $CODEDEPLOY_GROUP
  wait_until_deployed: true
  on:
    all_branches: true
